### ISSUE TITLE
[request] Start a collaboration with ImageGoNord

### ISSUE THREAD

**Issue by TheJoin95** [doprz/dipc#18]
Hi there,

I was looking into your implementation and I saw it's very similar to a 2020 project from https://github.com/Schrodinger-Hat/ImageGoNord

It's in python, it has a CLI as well as a website accessible for everyone.

Would you mind on collaborating with us there? It would be great 😃

**Comment by doprz** [comment]
Hi,

Thank you for your offer. I have to say that I just took a look and it looks like a really great project.
However, I've really enjoyed working with Rust and `dipc` so I will have to politely decline the offer.

This doesn't mean that I'm against contributing to IGN or Schrödinger Hat (great name by the way). Thank you once again and keep up the coding!
