### ISSUE TITLE
use of unstable library feature 'is_some_and'

### ISSUE THREAD

**Issue by doprz** [doprz/dipc#3]
Compiling after merging PR #1 causes this error at `src/main.rs:93:10`
`use of unstable library feature 'is_some_and'`

```rust
// Print palettes
let color = supports_color::on_cached(supports_color::Stream::Stdout)
    .is_some_and(|level| level.has_16m);
```

**Comment by CordlessCoder** [comment]
That was me forgetting to switch off of nightly. Whoops.

**Comment by CordlessCoder** [comment]
Can be rewritten as ```rs
    let color = matches!(supports_color::on_cached(supports_color::Stream::Stdout), Some(level) if level.has_16m);```

**Comment by doprz** [comment]
Fixed by:

```rust
// Print palettes
let color = match supports_color::on_cached(supports_color::Stream::Stdout) {
    Some(level) => level.has_16m,
    None => false,
};
```
