### ISSUE TITLE
Move to Indicatif

### ISSUE THREAD

**Issue by CordlessCoder** [doprz/dipc#6]
I suggest replacing the custom timing code and print statements with an indicatif-based Statusbar

- [ ] Statusbar for loading & processing themes
- [x] Statusbar for processing each image

**Comment by CordlessCoder** [comment]
I'm ready to start working on this as soon as my PR is merged

**Comment by doprz** [comment]
Good idea. I added some indicators in PR #5 as a temporary solution.

**Comment by doprz** [comment]
After this PR, I will add the timing code for the image(s) processing as part of the verbose cli flag.
I'd say don't remove the current print statements so that I can review your PR's changes and make an informed decision at a later time.

**Comment by doprz** [comment]
@CordlessCoder I pushed some changes and here are some thoughts:
- Adding a status bar for loading and processing the themes is unnecessary. `dipc` loaded + processed them so fast that the status bar didn't show up.
- I did add status bars for processing each image

**Comment by doprz** [comment]
I will be merging this and moving on to other features that are part of the `v1.0.0` release, but feel free to create another issue or PR if you want to add something.
